- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"

- name: Extract Node Exporter
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: yes

- name: Move Node Exporter binary to the correct location
  command: mv /usr/local/bin/node_exporter-1.8.2.linux-amd64/node_exporter /usr/local/bin/

- name: Create `node_exporter` user
  user:
    name: node_exporter
    shell: /sbin/nologin
    system: yes

- name: Copy systemd service file for Node Exporter
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify: restart node_exporter

- name: Reload systemd and start Node Exporter
  systemd:
    daemon_reload: yes
    name: node_exporter
    state: started
    enabled: yes

